project:
  type: book
  output-dir: docs

book:
  title: 'DS 2023 Final Project'
  author: 'Rebecca V. , Claire B. , Kayla K. , Iliana V.'
  favicon: logo.png
  description: Our final project for DS 2023 Communicating with Data
  keyword: blah blah
  url: https://github.com/clairembassett/DS-2023-Final-Project/tree/main
  sidebar:
    logo: logo.png
    search: true
  repo-url: https://github.com/clairembassett/DS-2023-Final-Project/tree/main
  repo-branch: master
  image: logo.png


  chapters: 
    - index.qmd
    - datacleaning.qmd
    - eda.qmd
    - dataviz.qmd
    - datadictionary.qmd


format:
  html:
    number-sections: true
    theme:
      light: minty
    code-fold: false
    backgroundcolor: "#FFFFFF"
